package ttgs.api.database.models;
// Generated May 30, 2016 7:45:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Courses generated by hbm2java
 */
@Entity
@Table(name="courses"
    ,catalog="ttdata"
)
public class Courses  implements java.io.Serializable {


     private Integer id;
     private Departments departments;
     private String name;
     private int userId;
     private String description;
     private Set<Students> studentses = new HashSet<Students>(0);
     private Set<Units> unitses = new HashSet<Units>(0);

    public Courses() {
    }

	
    public Courses(int userId, String description) {
        this.userId = userId;
        this.description = description;
    }
    public Courses(Departments departments, String name, int userId, String description, Set<Students> studentses, Set<Units> unitses) {
       this.departments = departments;
       this.name = name;
       this.userId = userId;
       this.description = description;
       this.studentses = studentses;
       this.unitses = unitses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="deptID")
    public Departments getDepartments() {
        return this.departments;
    }
    
    public void setDepartments(Departments departments) {
        this.departments = departments;
    }

    
    @Column(name="name", length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="user_id", nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }

    
    @Column(name="description", nullable=false, length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="courses")
    public Set<Students> getStudentses() {
        return this.studentses;
    }
    
    public void setStudentses(Set<Students> studentses) {
        this.studentses = studentses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="courses")
    public Set<Units> getUnitses() {
        return this.unitses;
    }
    
    public void setUnitses(Set<Units> unitses) {
        this.unitses = unitses;
    }




}


