package ttgs.api.database.models;
// Generated May 30, 2016 7:45:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Departments generated by hbm2java
 */
@Entity
@Table(name="departments"
    ,catalog="ttdata"
)
public class Departments  implements java.io.Serializable {


     private Integer id;
     private Schools schools;
     private String name;
     private Set<Courses> courseses = new HashSet<Courses>(0);

    public Departments() {
    }

	
    public Departments(Schools schools) {
        this.schools = schools;
    }
    public Departments(Schools schools, String name, Set<Courses> courseses) {
       this.schools = schools;
       this.name = name;
       this.courseses = courseses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sid", nullable=false)
    public Schools getSchools() {
        return this.schools;
    }
    
    public void setSchools(Schools schools) {
        this.schools = schools;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="departments")
    public Set<Courses> getCourseses() {
        return this.courseses;
    }
    
    public void setCourseses(Set<Courses> courseses) {
        this.courseses = courseses;
    }




}


