package ttgs.api.database.models;
// Generated May 30, 2016 7:45:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Lecturers generated by hbm2java
 */
@Entity
@Table(name="lecturers"
    ,catalog="ttdata"
)
public class Lecturers  implements java.io.Serializable {


     private Integer id;
     private String name;
     private int userId;
     private Set<Ttevents> tteventses = new HashSet<Ttevents>(0);
     private Set<Semesterunits> semesterunitses = new HashSet<Semesterunits>(0);

    public Lecturers() {
    }

	
    public Lecturers(int userId) {
        this.userId = userId;
    }
    public Lecturers(String name, int userId, Set<Ttevents> tteventses, Set<Semesterunits> semesterunitses) {
       this.name = name;
       this.userId = userId;
       this.tteventses = tteventses;
       this.semesterunitses = semesterunitses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="user_id", nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="lecturers")
    public Set<Ttevents> getTteventses() {
        return this.tteventses;
    }
    
    public void setTteventses(Set<Ttevents> tteventses) {
        this.tteventses = tteventses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="lecturers")
    public Set<Semesterunits> getSemesterunitses() {
        return this.semesterunitses;
    }
    
    public void setSemesterunitses(Set<Semesterunits> semesterunitses) {
        this.semesterunitses = semesterunitses;
    }




}


