package ttgs.api.database.models;
// Generated May 30, 2016 7:45:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Rooms generated by hbm2java
 */
@Entity
@Table(name="rooms"
    ,catalog="ttdata"
)
public class Rooms  implements java.io.Serializable {


     private Integer id;
     private Schools schools;
     private Integer size;
     private String name;
     private Integer type;
     private Set<Ttevents> tteventses = new HashSet<Ttevents>(0);

    public Rooms() {
    }

    public Rooms(Schools schools, Integer size, String name, Integer type, Set<Ttevents> tteventses) {
       this.schools = schools;
       this.size = size;
       this.name = name;
       this.type = type;
       this.tteventses = tteventses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sid")
    public Schools getSchools() {
        return this.schools;
    }
    
    public void setSchools(Schools schools) {
        this.schools = schools;
    }

    
    @Column(name="size")
    public Integer getSize() {
        return this.size;
    }
    
    public void setSize(Integer size) {
        this.size = size;
    }

    
    @Column(name="name", length=20)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="type")
    public Integer getType() {
        return this.type;
    }
    
    public void setType(Integer type) {
        this.type = type;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="rooms")
    public Set<Ttevents> getTteventses() {
        return this.tteventses;
    }
    
    public void setTteventses(Set<Ttevents> tteventses) {
        this.tteventses = tteventses;
    }




}


