package ttgs.api.database.models;
// Generated May 30, 2016 7:45:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Semesterunits generated by hbm2java
 */
@Entity
@Table(name="semesterunits"
    ,catalog="ttdata"
)
public class Semesterunits  implements java.io.Serializable {


     private Integer id;
     private Lecturers lecturers;
     private Stages stages;
     private Units units;
     private int lecturesInAWeek;
     private int userId;
     private String description;
     private Set<Ttevents> tteventses = new HashSet<Ttevents>(0);

    public Semesterunits() {
    }

	
    public Semesterunits(Stages stages, int lecturesInAWeek, int userId, String description) {
        this.stages = stages;
        this.lecturesInAWeek = lecturesInAWeek;
        this.userId = userId;
        this.description = description;
    }
    public Semesterunits(Lecturers lecturers, Stages stages, Units units, int lecturesInAWeek, int userId, String description, Set<Ttevents> tteventses) {
       this.lecturers = lecturers;
       this.stages = stages;
       this.units = units;
       this.lecturesInAWeek = lecturesInAWeek;
       this.userId = userId;
       this.description = description;
       this.tteventses = tteventses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="lecid")
    public Lecturers getLecturers() {
        return this.lecturers;
    }
    
    public void setLecturers(Lecturers lecturers) {
        this.lecturers = lecturers;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="stageid", nullable=false)
    public Stages getStages() {
        return this.stages;
    }
    
    public void setStages(Stages stages) {
        this.stages = stages;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="unitcode")
    public Units getUnits() {
        return this.units;
    }
    
    public void setUnits(Units units) {
        this.units = units;
    }

    
    @Column(name="lectures_in_a_week", nullable=false)
    public int getLecturesInAWeek() {
        return this.lecturesInAWeek;
    }
    
    public void setLecturesInAWeek(int lecturesInAWeek) {
        this.lecturesInAWeek = lecturesInAWeek;
    }

    
    @Column(name="user_id", nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }

    
    @Column(name="description", nullable=false, length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="semesterunits")
    public Set<Ttevents> getTteventses() {
        return this.tteventses;
    }
    
    public void setTteventses(Set<Ttevents> tteventses) {
        this.tteventses = tteventses;
    }




}


