package ttgs.api.database.models;
// Generated May 30, 2016 7:45:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Stages generated by hbm2java
 */
@Entity
@Table(name="stages"
    ,catalog="ttdata"
)
public class Stages  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set<Semesterunits> semesterunitses = new HashSet<Semesterunits>(0);
     private Set<Students> studentses = new HashSet<Students>(0);

    public Stages() {
    }

	
    public Stages(String name) {
        this.name = name;
    }
    public Stages(String name, Set<Semesterunits> semesterunitses, Set<Students> studentses) {
       this.name = name;
       this.semesterunitses = semesterunitses;
       this.studentses = studentses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=5)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="stages")
    public Set<Semesterunits> getSemesterunitses() {
        return this.semesterunitses;
    }
    
    public void setSemesterunitses(Set<Semesterunits> semesterunitses) {
        this.semesterunitses = semesterunitses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="stages")
    public Set<Students> getStudentses() {
        return this.studentses;
    }
    
    public void setStudentses(Set<Students> studentses) {
        this.studentses = studentses;
    }




}


