package ttgs.api.database.models;
// Generated May 30, 2016 7:45:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Students generated by hbm2java
 */
@Entity
@Table(name="students"
    ,catalog="ttdata"
)
public class Students  implements java.io.Serializable {


     private Integer id;
     private Courses courses;
     private Stages stages;
     private Integer number;
     private String description;
     private Set<Ttevents> tteventses = new HashSet<Ttevents>(0);

    public Students() {
    }

	
    public Students(Stages stages, String description) {
        this.stages = stages;
        this.description = description;
    }
    public Students(Courses courses, Stages stages, Integer number, String description, Set<Ttevents> tteventses) {
       this.courses = courses;
       this.stages = stages;
       this.number = number;
       this.description = description;
       this.tteventses = tteventses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="courseID")
    public Courses getCourses() {
        return this.courses;
    }
    
    public void setCourses(Courses courses) {
        this.courses = courses;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="stageid", nullable=false)
    public Stages getStages() {
        return this.stages;
    }
    
    public void setStages(Stages stages) {
        this.stages = stages;
    }

    
    @Column(name="number")
    public Integer getNumber() {
        return this.number;
    }
    
    public void setNumber(Integer number) {
        this.number = number;
    }

    
    @Column(name="description", nullable=false, length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="students")
    public Set<Ttevents> getTteventses() {
        return this.tteventses;
    }
    
    public void setTteventses(Set<Ttevents> tteventses) {
        this.tteventses = tteventses;
    }




}


