package ttgs.api.database.models;
// Generated May 30, 2016 7:45:52 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Ttevents generated by hbm2java
 */
@Entity
@Table(name="ttevents"
    ,catalog="ttdata"
    , uniqueConstraints = @UniqueConstraint(columnNames={"lecturerid", "roomid", "semunitid", "timestart", "timeend", "day"}) 
)
public class Ttevents  implements java.io.Serializable {


     private Integer tteventid;
     private Lecturers lecturers;
     private Rooms rooms;
     private Semesterunits semesterunits;
     private Students students;
     private Date timestart;
     private Date timeend;
     private String day;
     private String description;

    public Ttevents() {
    }

    public Ttevents(Lecturers lecturers, Rooms rooms, Semesterunits semesterunits, Students students, Date timestart, Date timeend, String day, String description) {
       this.lecturers = lecturers;
       this.rooms = rooms;
       this.semesterunits = semesterunits;
       this.students = students;
       this.timestart = timestart;
       this.timeend = timeend;
       this.day = day;
       this.description = description;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="tteventid", unique=true, nullable=false)
    public Integer getTteventid() {
        return this.tteventid;
    }
    
    public void setTteventid(Integer tteventid) {
        this.tteventid = tteventid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="lecturerid", nullable=false)
    public Lecturers getLecturers() {
        return this.lecturers;
    }
    
    public void setLecturers(Lecturers lecturers) {
        this.lecturers = lecturers;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="roomid", nullable=false)
    public Rooms getRooms() {
        return this.rooms;
    }
    
    public void setRooms(Rooms rooms) {
        this.rooms = rooms;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="semunitid", nullable=false)
    public Semesterunits getSemesterunits() {
        return this.semesterunits;
    }
    
    public void setSemesterunits(Semesterunits semesterunits) {
        this.semesterunits = semesterunits;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="studentid", nullable=false)
    public Students getStudents() {
        return this.students;
    }
    
    public void setStudents(Students students) {
        this.students = students;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="timestart", nullable=false, length=19)
    public Date getTimestart() {
        return this.timestart;
    }
    
    public void setTimestart(Date timestart) {
        this.timestart = timestart;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="timeend", nullable=false, length=19)
    public Date getTimeend() {
        return this.timeend;
    }
    
    public void setTimeend(Date timeend) {
        this.timeend = timeend;
    }

    
    @Column(name="day", nullable=false, length=4)
    public String getDay() {
        return this.day;
    }
    
    public void setDay(String day) {
        this.day = day;
    }

    
    @Column(name="description", nullable=false, length=100)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


