package ttgs.api.database.models;
// Generated May 30, 2016 7:45:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Units generated by hbm2java
 */
@Entity
@Table(name="units"
    ,catalog="ttdata"
)
public class Units  implements java.io.Serializable {


     private String code;
     private Courses courses;
     private String name;
     private Set<Semesterunits> semesterunitses = new HashSet<Semesterunits>(0);

    public Units() {
    }

	
    public Units(String code) {
        this.code = code;
    }
    public Units(String code, Courses courses, String name, Set<Semesterunits> semesterunitses) {
       this.code = code;
       this.courses = courses;
       this.name = name;
       this.semesterunitses = semesterunitses;
    }
   
     @Id 

    
    @Column(name="code", unique=true, nullable=false, length=10)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="courseID")
    public Courses getCourses() {
        return this.courses;
    }
    
    public void setCourses(Courses courses) {
        this.courses = courses;
    }

    
    @Column(name="name", length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="units")
    public Set<Semesterunits> getSemesterunitses() {
        return this.semesterunitses;
    }
    
    public void setSemesterunitses(Set<Semesterunits> semesterunitses) {
        this.semesterunitses = semesterunitses;
    }




}


