package ttgs.api.database.models;
// Generated May 30, 2016 7:45:52 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * University generated by hbm2java
 */
@Entity
@Table(name="university"
    ,catalog="ttdata"
)
public class University  implements java.io.Serializable {


     private String name;
     private int number;
     private Date startTime;
     private Date endTime;
     private Date lunchTime;
     private Date lectureDuration;
     private Date lunchDuration;

    public University() {
    }

    public University(String name, int number, Date startTime, Date endTime, Date lunchTime, Date lectureDuration, Date lunchDuration) {
       this.name = name;
       this.number = number;
       this.startTime = startTime;
       this.endTime = endTime;
       this.lunchTime = lunchTime;
       this.lectureDuration = lectureDuration;
       this.lunchDuration = lunchDuration;
    }
   
     @Id 

    
    @Column(name="name", unique=true, nullable=false, length=200)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="number", nullable=false)
    public int getNumber() {
        return this.number;
    }
    
    public void setNumber(int number) {
        this.number = number;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="start_time", nullable=false, length=8)
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="end_time", nullable=false, length=8)
    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="lunch_time", nullable=false, length=8)
    public Date getLunchTime() {
        return this.lunchTime;
    }
    
    public void setLunchTime(Date lunchTime) {
        this.lunchTime = lunchTime;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="lecture_duration", nullable=false, length=8)
    public Date getLectureDuration() {
        return this.lectureDuration;
    }
    
    public void setLectureDuration(Date lectureDuration) {
        this.lectureDuration = lectureDuration;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="lunch_duration", nullable=false, length=8)
    public Date getLunchDuration() {
        return this.lunchDuration;
    }
    
    public void setLunchDuration(Date lunchDuration) {
        this.lunchDuration = lunchDuration;
    }




}


